name: Node.js CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: write

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js 20.x
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build application
              run: npm run build

            - name: Run Jest tests
              run: npm run test:jest

            - name: Archive build artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: build-artifacts
                  path: build/

    robot-tests:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Download build artifacts
              uses: actions/download-artifact@v3
              with:
                  name: build-artifacts
                  path: build/

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install Robot Framework
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  rfbrowser init

            - name: Run tests with server
              run: |
                  npx serve -s build -l 3000 &
                  SERVER_PID=$!

                  # Wait for server with retry
                  for i in {1..10}; do
                    if curl --silent --fail http://localhost:3000 > /dev/null; then
                      echo "Server started successfully"
                      break
                    fi
                    echo "Waiting for server (attempt $i)..."
                    sleep 3
                    if [ $i -eq 10 ]; then
                      echo "Server failed to start"
                      kill $SERVER_PID
                      exit 1
                    fi
                  done

                  # Run tests and capture exit code
                  robot --outputdir results tests/robot/
                  TEST_EXIT=$?

                  # Cleanup server
                  kill $SERVER_PID

                  # Return test result
                  exit $TEST_EXIT

            - name: Upload test results
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: robot-test-results
                  path: results/
