name: Node.js CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: write

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Build with Vite
              run: npm run build

            - name: Run Jest tests
              run: npm run test:jest

    robot-tests:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"
                  cache: "npm"

            - name: Install dependencies again
              run: npm ci

            - name: Build with Vite again
              run: npm run build

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                  python-version: "3.12"

            - name: Install Robot Framework and Browser
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  rfbrowser init

            - name: Start server in background
              run: npm run preview -- --port 3000 &

            - name: Wait for server to start
              run: |
                  for i in {1..10}; do
                    if curl --silent --fail http://localhost:3000 > /dev/null; then
                      echo "Server is ready!"
                      break
                    fi
                    if [ $i -eq 10 ]; then
                      echo "Server failed to start."
                      exit 1
                    fi
                    sleep 3
                  done

            - name: Run Robot Framework Tests
              run: robot --outputdir results tests/robot/

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: robot-test-results
                  path: results/
