name: Node.js CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch:

permissions:
    contents: read
    pull-requests: write

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20.x
                  cache: "npm"

            - name: Install dependencies
              run: npm ci

            - name: Run Jest tests
              run: npm run test:jest

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install Robot Framework
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  rfbrowser init

            - name: Build application
              run: npm run build

            - name: Run Robot tests
              run: |
                  npx serve -s build -l 3000 &
                  SERVER_PID=$!

                  # Verify server is running
                  for i in {1..10}; do
                    if curl --silent --fail http://localhost:3000 > /dev/null; then
                      break
                    fi
                    if [ $i -eq 10 ]; then
                      kill $SERVER_PID
                      exit 1
                    fi
                    sleep 2
                  done

                  # Run tests
                  robot --outputdir results tests/robot/
                  TEST_EXIT=$?
                  kill $SERVER_PID
                  exit $TEST_EXIT

            - name: Upload test results
              uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: robot-test-results
                  path: results/
