# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code, and run tests across different versions of Node.js
name: Node.js CI

on:
    push:
        branches: ["master"]
    pull_request:
        branches: ["master"]
    workflow_dispatch: # Allow manual triggering

permissions:
    contents: read
    pull-requests: write

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20.x]
        steps:
            - uses: actions/checkout@v4

            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"

            - name: Install Node.js dependencies
              run: npm ci

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Install Robot Framework and Browser Library
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  rfbrowser init

            - name: Verify Python Environment
              run: |
                  python --version
                  pip list

            - name: Build app
              run: npm run build --if-present

            - name: Run tests
              run: npm test

    robot-tests:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: "20.x"

            - name: Install dependencies
              run: npm ci

            - name: Build app
              run: npm run build

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.10"

            - name: Verify Python Environment
              run: |
                  python --version
                  pip list

            - name: Install Robot Framework and Browser Library
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
                  rfbrowser init

            - name: Start server in background
              run: npx serve -s build -l 3000 &

            - name: Wait for server to start
              run: |
                  for i in {1..10}; do
                      curl --fail http://localhost:3000 && break
                      echo "Waiting for server to start..."
                      sleep 3
                  done

            - name: Verify Server is Running
              run: curl --fail http://localhost:3000 || exit 1

            - name: Run Robot Framework Tests
              run: robot --outputdir results tests/robot/

            - name: Upload test results
              uses: actions/upload-artifact@v3
              if: always()
              with:
                  name: robot-test-results
                  path: results/
